/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.liferay.sample.service.persistence.AddressPK;

import java.io.Serializable;

/**
 * The base model interface for the Address service. Represents a row in the &quot;SAMPLE_Address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.AddressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.AddressImpl}.
 * </p>
 *
 * @author NeerajGautam
 * @see Address
 * @see com.liferay.sample.model.impl.AddressImpl
 * @see com.liferay.sample.model.impl.AddressModelImpl
 * @generated
 */
public interface AddressModel extends BaseModel<Address> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a address model instance should use the {@link Address} interface instead.
	 */

	/**
	 * Returns the primary key of this address.
	 *
	 * @return the primary key of this address
	 */
	public AddressPK getPrimaryKey();

	/**
	 * Sets the primary key of this address.
	 *
	 * @param primaryKey the primary key of this address
	 */
	public void setPrimaryKey(AddressPK primaryKey);

	/**
	 * Returns the address ID of this address.
	 *
	 * @return the address ID of this address
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this address.
	 *
	 * @param addressId the address ID of this address
	 */
	public void setAddressId(long addressId);

	/**
	 * Returns the employee ID of this address.
	 *
	 * @return the employee ID of this address
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this address.
	 *
	 * @param employeeId the employee ID of this address
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the address of this address.
	 *
	 * @return the address of this address
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this address.
	 *
	 * @param address the address of this address
	 */
	public void setAddress(String address);

	/**
	 * Returns the contact no of this address.
	 *
	 * @return the contact no of this address
	 */
	public int getContactNo();

	/**
	 * Sets the contact no of this address.
	 *
	 * @param contactNo the contact no of this address
	 */
	public void setContactNo(int contactNo);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Address address);

	public int hashCode();

	public CacheModel<Address> toCacheModel();

	public Address toEscapedModel();

	public Address toUnescapedModel();

	public String toString();

	public String toXmlString();
}